#服务配置
server:
  host: 'localhost'
  prot: 4008
#数据库配置
mysql:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'study'
  password: '12345678'
  database: 'study'
  logging: false
  poolSize: 10
  connectorPackage: 'mysql2'
  charset: 'utf8mb4'
  synchronize: true
#redis配置
redis:
  enable: true
  host: 'localhost'
  port: 6379
  enableAuth: false
jwt:
  #秘钥
  secret: 'zhao'
  # 过期时间，表示7天过期
  expiresIn: '7d'
#日志级别
logger:
  level: 'info'
